---
- name:  create  node
  hosts: all
  connection: local
  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.6"
      name: "webserv1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: 6.6.6.1
      name: webserv2
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: 6.6.6.2
      name: webserv3
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: 6.6.6.3
      name: webserv4
